# Generated by Django 5.1.3 on 2024-12-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rugby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=40)),
                ('talle', models.IntegerField()),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
